apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-frontend-deployment
  labels:
    app: k8s-frontend-deployment
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: k8s-frontend
  template:
    metadata:
      labels:
        app: k8s-frontend
    spec:
      volumes:
        - name: k8s-frontend-volume-images
          emptyDir: {}
      containers:
        - name: k8s-frontend
          image: rihabbennour/frontend
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
          ports:
            - name: http
              containerPort: 80
          env:
            - name: BASE_API_URL
              value: api-service
            - name: PROFILE
              value: PRODUCTION
          livenessProbe:
            httpGet:
              port: 80
              path: /ping/health
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /usr/share/nginx/images
              name: k8s-frontend-volume-images

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-frontend-service
  labels:
    app: k8s-frontend-service
spec:
  selector:
    app: k8s-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30017

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-frontend-ingress
  labels:
    app: k8s-frontend-ingress
spec:
  rules:
    - host: k8s.frontend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k8s-frontend-service
                port:
                  number: 80
